export const defaultConfig = {
  version: '1.0.0',
  apiKeys: {
    anthropic: '',
    openai: '',
    gemini: '',
    groq: '',
    ollama: 'http://localhost:11434',
    elevenlabs: '',
    tavily: '',
    serper: '',
    brave: '',
    firecrawl: '',
    nanobrowser: '',
    telegram: { botToken: '', allowedUserId: '' },
  },
  models: {
    default: 'claude-opus-4-5',
    provider: 'anthropic',
    fallback: 'gpt-4o',
    fallbackProvider: 'openai',
  },
  mcps: {
    github: { enabled: false, token: '' },
    supabase: { enabled: false, url: '', serviceKey: '' },
    vercel: { enabled: false, token: '' },
    railway: { enabled: false, token: '' },
    slack: { enabled: false, botToken: '', teamId: '' },
    gmail: { enabled: false },
    cloudflare: { enabled: false, apiToken: '', accountId: '' },
    netlify: { enabled: false, token: '' },
    stripe: { enabled: false, secretKey: '' },
    custom: [] as any[],
  },
  skills: { installed: [] as string[], enabled: [] as string[] },
  ui: { theme: 'system', fontSize: 'medium', sidebarOpen: true },
  telegram: { enabled: false, runOnStartup: false },
}
